apiVersion: apps/v1
kind: Deployment
metadata:
  name: catatan-sederhana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catatan-sederhana
  template:
    metadata:
      labels:
        app: catatan-sederhana
    spec:
      containers:
        - name: laravel
          image: docker.io/<dockerhub-username>/catatan-sederhana_test:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: APP_ENV
              value: "production"
            - name: DB_CONNECTION
              value: "sqlite"
            - name: DB_DATABASE
              value: "/app/database/database.sqlite"
