apiVersion: apps/v1
kind: Deployment
metadata:
  name: catatan-sederhana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catatan-sederhana
  template:
    metadata:
      labels:
        app: catatan-sederhana
    spec:
      containers:
        - name: laravel
          image: username_dockerhub/catatan-sederhana:latest
          ports:
            - containerPort: 8000
          command: ["php"]
          args:
            ["artisan", "serve", "--host=0.0.0.0", "--port=8000"]
          env:
          - name: APP_ENV
            value: "production"

          - name: APP_DEBUG
            value: "false"

          - name: APP_KEY
            value: "base64:12pBkfT/k4qamfpFGovJpYyHuOKkjZ20p8UL2x8aHD0="

          - name: DB_CONNECTION
            value: mysql

          - name: DB_HOST
            value: mysql

          - name: DB_PORT
            value: "3306"

          - name: DB_DATABASE
            value: laravel

          - name: DB_USERNAME
            value: laravel
            
          - name: DB_PASSWORD
            value: laravel