apiVersion: apps/v1
kind: Deployment
metadata:
  name: catatan-sederhana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catatan-sederhana
  template:
    metadata:
      labels:
        app: catatan-sederhana
    spec:
      containers:
        - name: laravel
          image: username_dockerhub/catatan-sederhana:latest
          ports:
            - containerPort: 8000
          command: ["php"]
          args:
            ["artisan", "serve", "--host=0.0.0.0", "--port=8000"]
