apiVersion: v1
kind: Service
metadata:
  name: catatan-sederhana-test-service
spec:
  selector:
    app: catatan-sederhana_test
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30080
